# Generated by Django 5.0.2 on 2025-04-02 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'ordering': ['position'], 'verbose_name': 'Трек в плейлисте', 'verbose_name_plural': 'Треки в плейлистах'},
        ),
        migrations.RemoveField(
            model_name='track',
            name='disgen_music_id',
        ),
        migrations.RemoveField(
            model_name='track',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='track',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
