# Generated by Django 5.0.2 on 2025-04-04 17:27

import django.db.models.deletion
import music.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_userlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['album', 'track_number', '-created_at'], 'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AddField(
            model_name='track',
            name='track_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер трека'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/', validators=[music.models.validate_audio_file], verbose_name='Аудио файл'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='track',
            name='play_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество прослушиваний'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('artist', models.CharField(max_length=200, verbose_name='Исполнитель')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='album_covers/', verbose_name='Обложка')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album', verbose_name='Альбом'),
        ),
    ]
