# Generated by Django 5.0.2 on 2025-05-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_supportticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_explicit',
            field=models.BooleanField(default=False, verbose_name='Есть цензура'),
        ),
    ]
